---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - files:
      - dashboards/cluster.json
      - dashboards/control-plane.json
      - dashboards/logs.json
    name: flux-grafana-dashboards
    options:
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/part-of: flux
        grafana_dashboard: "1"
        kustomize.toolkit.fluxcd.io/substitute: disabled
resources:
  - podmonitor.yaml

namespace: monitoring
