---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - args:
            - dashboard
          envFrom:
            - configMapRef:
                name: prowler-envs
          image: toniblyx/prowler
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          name: prowler
          ports:
            - containerPort: 11666
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /home/prowler/output
              name: prowler-output
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: []
        sysctls: []
      serviceAccountName: prowler
      terminationGracePeriodSeconds: 1
      volumes:
        - emptyDir: {}
          name: prowler-output
