configMapGenerator:
  - name: prowler-envs
    envs:
      - configs.env

resources:
  - service.yml
  - serviceaccount.yml
  - deployment.yml

images:
  - name: toniblyx/prowler
    newTag: 5.0.5

labels:
  - pairs:
      app.kubernetes.io/component: prowler
      app.kubernetes.io/instance: prowler
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: prowler
      app.kubernetes.io/part-of: prowler
      app.kubernetes.io/version: 1.0.0
    includeSelectors: true
