---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prowler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prowler
subjects:
  - kind: ServiceAccount
    name: prowler
    namespace: prowler
