---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prowler
rules:
  - apiGroups: ["apps"]
    resourceNames: ["prowler"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
