---
configMapGenerator:
  - name: oathkeeper-config
    files:
      - config.yml=oathkeeper-server-config.yml
  - name: oathkeeper-envs
    envs:
      - configs.env

images:
  - name: oryd/oathkeeper
    newTag: v0.40.7-distroless
  - name: oryd/oathkeeper-maester
    newTag: v0.1.10-arm64
  - name: bitnami/kubectl
    newTag: 1.31.1

commonLabels:
  app.kubernetes.io/managed-by: Kustomize
  app.kubernetes.io/name: oathkeeper
  app.kubernetes.io/part-of: oathkeeper
  app.kubernetes.io/version: v1.0.0

replacements:
  - source:
      kind: Deployment
      name: oathkeeper
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterRoleBinding
          name: oathkeeper-maester-role-binding
        fieldPaths:
          - subjects.[kind=ServiceAccount].namespace
        options:
          create: true
  - source:
      kind: Deployment
      name: oathkeeper
      fieldPath: spec.template.metadata.labels
    targets:
      - select:
          kind: VMServiceScrape
          name: oathkeeper-metrics
        fieldPaths:
          - spec.selector.matchLabels
        options:
          create: true
      - select:
          kind: Service
          name: oathkeeper-metrics
        fieldPaths:
          - spec.selector
        options:
          create: true
      - select:
          kind: Service
          name: oathkeeper-api
        fieldPaths:
          - spec.selector
        options:
          create: true
      - select:
          kind: Service
          name: oathkeeper-proxy
        fieldPaths:
          - spec.selector
        options:
          create: true
  - source:
      kind: Deployment
      name: oathkeeper-maester
      fieldPath: spec.template.metadata.labels
    targets:
      - select:
          kind: VMServiceScrape
          name: oathkeeper-maester
        fieldPaths:
          - spec.selector.matchLabels
        options:
          create: true
      - select:
          kind: Service
          name: oathkeeper-maester-metrics
        fieldPaths:
          - spec.selector
        options:
          create: true
  - source:
      kind: Service
      name: oathkeeper-metrics
      fieldPath: metadata.labels
    targets:
      - select:
          kind: VMServiceScrape
          name: oathkeeper
        fieldPaths:
          - spec.selector.matchLabels
        options:
          create: true
  - source:
      kind: Service
      name: oathkeeper-maester-metrics
      fieldPath: metadata.labels
    targets:
      - select:
          kind: VMServiceScrape
          name: oathkeeper-maester
        fieldPaths:
          - spec.selector.matchLabels
        options:
          create: true

resources:
  # - https://github.com/ory/oathkeeper-maester//config/crd?timeout=30s&ref=v0.1.10
  - crds.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - service-oathkeeper-api.yml
  - service-oathkeeper-metrics.yml
  - service-oathkeeper-proxy.yml
  - service-oathkeeper-maester-metrics.yml
  - serviceaccount.yml
  - deployment-oathkeeper-maester.yml
  - deployment-oathkeeper.yml
  - vmservicescrape-oathkeeper.yml
  - vmservicescrape-oathkeeper-maester.yml

namespace: auth
