---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oathkeeper
  labels:
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/component: oathkeeper-metrics
spec:
  endpoints:
    - interval: 60s
      path: /metrics/prometheus
      port: http
      scheme: http
      scrapeTimeout: 30s
