---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: redis-commander-envs
    envs:
      - configs.env

images:
  - name: ghcr.io/joeferner/redis-commander
    newTag: 0.9.1

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: redis-commander
      app.kubernetes.io/instance: redis-commander
      app.kubernetes.io/managed-by: Kustomize
      app.kubernetes.io/name: redis-commander
      app.kubernetes.io/part-of: redis-commander
      app.kubernetes.io/version: v1.0.0

resources:
  - deployment.yml
  - service.yml
  - serviceaccount.yml
