access_rules:
  matching_strategy: regexp
  repositories:
    - file:///etc/rules/access-rules.json
authenticators:
  anonymous:
    config:
      subject: guest
    enabled: true
  cookie_session:
    config:
      check_session_url: http://kratos-public.auth/sessions/whoami
      extra_from: "@this"
      force_method: GET
      only:
        - ory_kratos_session
      preserve_path: true
      preserve_query: true
      subject_from: identity.id
    enabled: true
  bearer_token:
    enabled: true
    config:
      check_session_url: http://kratos-public.auth/sessions/whoami
      extra_from: "@this"
      force_method: GET
      forward_http_headers:
        - x-session-token
      preserve_path: true
      subject_from: identity.id
      token_from:
        header: x-session-token
  oauth2_client_credentials:
    enabled: true
    config:
      token_url: http://hydra-public.auth/oauth2/token
      retry:
        give_up_after: "2s"
        max_delay: "1s"
      cache:
        enabled: true
        ttl: 60s
        max_tokens: 300
      required_scope: []
  oauth2_introspection:
    config:
      introspection_url: http://hydra-admin.auth/admin/oauth2/introspect
      required_scope: []
      cache:
        enabled: true
        ttl: 300s
    enabled: true
  jwt:
    config:
      jwks_urls:
        - http://hydra-public.auth/.well-known/jwks.json
    enabled: true
  noop:
    enabled: true
  unauthorized:
    enabled: true
authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
  remote_json:
    config:
      payload: ""
      remote: http://keto-read.auth/relation-tuples/check
    enabled: true
errors:
  fallback:
    - redirect
    - json
  handlers:
    json:
      config:
        verbose: true
      enabled: true
    redirect:
      config:
        return_to_query_param: return_to
        to: https://auth.developer-friendly.blog/login
        when:
          - error:
              - unauthorized
      enabled: true
log:
  format: json
  leak_sensitive_values: true
  level: debug
mutators:
  header:
    config:
      headers: {}
    enabled: true
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: https://oauth2.developer-friendly.blog
      jwks_url: http://hydra-public.auth/.well-known/jwks.json
serve:
  api:
    port: 4456
  prometheus:
    port: 9000
  proxy:
    port: 4455
    timeout:
      read: 60m
      idle: 60m
      write: 60m
    cors:
      enabled: true
      allowed_headers:
        - accept
        - content-type
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowed_origins:
        - https://*.developer-friendly.blog
      allow_credentials: true
      debug: false
# tracing:
#   provider: jaeger
#   providers:
#     jaeger:
#       local_agent_address: jaeger.monitoring:6831
#       sampling:
#         server_url: http://jaeger.monitoring:5778/sampling
#   service_name: oathkeeper
