---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: oathkeeper
spec:
  endpoints:
    - interval: 60s
      path: /metrics/prometheus
      port: http-metrics
      scheme: http
      scrapeTimeout: 30s
