apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: oathkeeper-maester
  labels:
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/component: oathkeeper-maester-metrics
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
