configMapGenerator:
  - files:
      - config.yml=kratos-server-config.yml
    name: kratos-config

resources:
  - ../../base

images:
  - name: oryd/kratos
    newTag: v1.3.1-distroless

patches:
  - path: patch-deployment.yml
    target:
      kind: Deployment
      name: kratos

namespace: auth
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
