---
resources:
  - ../../base
  - vmservicescrape.yml

replacements:
  - source:
      kind: Service
      name: oathkeeper-maester-metrics
      fieldPath: metadata.labels
    targets:
      - select:
          kind: VMServiceScrape
          name: oathkeeper-maester
        fieldPaths:
          - spec.selector.matchLabels
        options:
          create: true

namespace: auth
