apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kratos-admin
spec:
  endpoints:
    - interval: 30s
      path: /admin/metrics/prometheus
      port: http-admin
      scheme: http
      scrapeTimeout: 10s
