---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-admin-ui
spec:
  template:
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: kratos-admin-ui-envs
          image: ghcr.io/meysam81/kratos-admin-ui
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: kratos-admin-ui
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kratos-admin-ui
