---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hydra-maester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hydra-maester
subjects:
  - kind: ServiceAccount
    name: hydra-maester
    namespace: ""
