---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hydra-maester
rules:
  - apiGroups:
      - hydra.ory.sh
    resources:
      - oauth2clients
      - oauth2clients/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
      - create
