---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra-hydra-maester
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - "--metrics-addr=0.0.0.0:8080"
            - "--hydra-url=http://hydra-admin"
            - "--hydra-port=4445"
            - "--endpoint=/admin/clients"
          command:
            - /manager
          image: oryd/hydra-maester
          imagePullPolicy: IfNotPresent
          name: hydra-maester
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: hydra-maester
      terminationGracePeriodSeconds: 60
