resources:
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml
  - role.yml
  - rolebinding.yml
  - service.yml
  - serviceaccount.yml

images:
  - name: oryd/hydra-maester

replacements:
  - source:
      kind: ServiceAccount
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterRoleBinding
        fieldPaths:
          - subjects.0.namespace
        options:
          create: true
      - select:
          kind: RoleBinding
        fieldPaths:
          - subjects.0.namespace
        options:
          create: true

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: hydra-maester
      app.kubernetes.io/instance: hydra-maester
      app.kubernetes.io/managed-by: Kustomize
      app.kubernetes.io/name: hydra-maester
      app.kubernetes.io/part-of: hydra-maester
      app.kubernetes.io/version: v1.0.0

namespace: auth
