---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hydra-maester
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hydra-maester
subjects:
  - kind: ServiceAccount
    name: hydra-maester
    namespace: ""
