---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hydra-maester
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - hydra.ory.sh
    resources:
      - oauth2clients
      - oauth2clients/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
