---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: oryd/oathkeeper
  - name: bitnami/kubectl

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: oathkeeper
      app.kubernetes.io/instance: oathkeeper
      app.kubernetes.io/managed-by: Kustomize
      app.kubernetes.io/name: oathkeeper
      app.kubernetes.io/part-of: oathkeeper
      app.kubernetes.io/version: v1.0.0

resources:
  - service-api.yml
  - service-metrics.yml
  - service-proxy.yml
  - serviceaccount.yml
  - deployment.yml
