---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - files:
      - config.yml=oathkeeper-server-config.yml
    name: oathkeeper-config
  - envs:
      - configs.env
    name: oathkeeper-envs

images:
  - name: oryd/oathkeeper
    newTag: v0.40.7-distroless
  - name: bitnami/kubectl
    newTag: 1.31.2

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: oathkeeper
      app.kubernetes.io/instance: oathkeeper
      app.kubernetes.io/managed-by: Kustomize
      app.kubernetes.io/name: oathkeeper
      app.kubernetes.io/part-of: oathkeeper
      app.kubernetes.io/version: v1.0.0

resources:
  - service-api.yml
  - service-metrics.yml
  - service-proxy.yml
  - serviceaccount.yml
  - deployment.yml
