---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-api
  labels:
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/component: oathkeeper-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-api
  type: ClusterIP
