---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-metrics
  labels:
    prometheus.io/instance: oathkeeper-metrics
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-metrics
  type: ClusterIP
