apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-metrics
  labels:
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/component: oathkeeper-metrics
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-metrics
  type: ClusterIP
