apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-maester-metrics
  labels:
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/component: oathkeeper-maester-metrics
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: metrics
  type: ClusterIP
