---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: hydra
spec:
  endpoints:
    - interval: 30s
      path: /admin/metrics/prometheus
      port: hydra-admin
      scheme: http
      scrapeTimeout: 10s
