apiVersion: v1
kind: Service
metadata:
  name: kratos-courier
  labels:
    component: kratos-courier
spec:
  ports:
    - name: http-courier
      port: 80
      protocol: TCP
      targetPort: http-courier
  type: ClusterIP
