apiVersion: v1
kind: Service
metadata:
  name: kratos-admin
  labels:
    component: kratos-admin
spec:
  ports:
    - name: http-admin
      port: 80
      protocol: TCP
      targetPort: http-admin
  type: ClusterIP
