apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pod-identity-webhook
spec:
  secretName: pod-identity-webhook-cert
  commonName: pod-identity-webhook.NAMESPACE.svc
  dnsNames:
    - pod-identity-webhook
    - pod-identity-webhook.NAMESPACE
    - pod-identity-webhook.NAMESPACE.svc
    - pod-identity-webhook.NAMESPACE.svc.cluster.local
  isCA: true
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
