---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-identity-webhook
spec:
  replicas: 1
  template:
    spec:
      containers:
        - command:
            - /webhook
            - --in-cluster=false
            - --namespace=$(POD_NAMESPACE)
            - --service-name=pod-identity-webhook
            - --annotation-prefix=eks.amazonaws.com
            - --token-audience=sts.amazonaws.com
            - --logtostderr
            - --v=5
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: amazon/amazon-eks-pod-identity-webhook
          name: pod-identity-webhook
          ports:
            - containerPort: 443
              name: https
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: cert
              readOnly: true
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: pod-identity-webhook
      volumes:
        - name: cert
          secret:
            secretName: pod-identity-webhook-cert
