---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  name: pod-identity-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
