---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9999"
    prometheus.io/scrape: "true"
  name: pod-identity-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: metrics
      port: 9999
      targetPort: metrics
