apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kratos
spec:
  data:
    - remoteRef:
        key: /kratos/dsn
      secretKey: DSN
    - remoteRef:
        key: /kratos/courier/smtp/connection-uri
      secretKey: COURIER_SMTP_CONNECTION_URI
    - remoteRef:
        key: /kratos/secrets/cookie/0
      secretKey: SECRETS_COOKIE_0
    - remoteRef:
        key: /kratos/secrets/cipher/0
      secretKey: SECRETS_CIPHER_0
    - remoteRef:
        key: /kratos/secrets/default/0
      secretKey: SECRETS_DEFAULT_0
    - remoteRef:
        key: /kratos/oidc/google/client-id
      secretKey: SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
    - remoteRef:
        key: /kratos/oidc/google/client-secret
      secretKey: SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    immutable: false
    template:
      mergePolicy: Replace
      type: Opaque
