cookies:
  domain: .developer-friendly.blog
  path: /
  same_site: None
courier:
  smtp:
    connection_uri: OVERRIDDEN_BY_ENVS
    from_address: auth@mailing.developer-friendly.blog
    from_name: Developer Friendly Blog
  template_override_path: /conf/courier-templates
dsn: OVERRIDDEN_BY_ENVS
hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 16
identity:
  default_schema_id: admin
  schemas:
    - id: admin
      url: file:///etc/kratos-schemas/admin.schema.json
log:
  format: json
  leak_sensitive_values: true
  level: debug
secrets:
  cipher:
    - OVERRIDDEN_BY_ENVS
  cookie:
    - OVERRIDDEN_BY_ENVS
ciphers:
  algorithm: xchacha20-poly1305
selfservice:
  allowed_return_urls:
    - https://*.developer-friendly.blog/
    - http://*.developer-friendly.blog/
  default_browser_return_url: https://auth.developer-friendly.blog
  flows:
    error:
      ui_url: https://auth.developer-friendly.blog/error
    login:
      before:
        hooks:
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: true
              url: http://echo-server.default/login/before
            hook: web_hook
      after:
        default_browser_return_url: https://auth.developer-friendly.blog/sessions
        hooks:
          - hook: revoke_active_sessions
          - hook: require_verified_address
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: true
              url: http://echo-server.default/login/after
            hook: web_hook
      lifespan: 1h
      ui_url: https://auth.developer-friendly.blog/login
    logout:
      after:
        default_browser_return_url: https://auth.developer-friendly.blog
    recovery:
      before:
        hooks:
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: true
              url: http://echo-server.default/recovery/before
            hook: web_hook
      after:
        default_browser_return_url: https://auth.developer-friendly.blog/login
        hooks:
          - hook: revoke_active_sessions
      enabled: true
      ui_url: https://auth.developer-friendly.blog/recovery
      use: link
    registration:
      before:
        hooks:
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: true
              url: http://echo-server.default/registration/before
            hook: web_hook
      after:
        default_browser_return_url: https://auth.developer-friendly.blog/sessions
        hooks:
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: true
              url: http://echo-server.default/registration/after
            hook: web_hook
        oidc:
          hooks:
            - hook: session
        # password:
        #   hooks:
        #     - hook: show_verification_ui
      enabled: false
      lifespan: 1h
      ui_url: https://auth.developer-friendly.blog/registration
    settings:
      before:
        hooks:
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: true
              url: http://echo-server.default/settings/before
            hook: web_hook
      after:
        hooks:
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: false
              url: http://echo-server.default/settings/after
            hook: web_hook
      privileged_session_max_age: 15m
      required_aal: highest_available
      ui_url: https://auth.developer-friendly.blog/settings
    verification:
      before:
        hooks:
          - config:
              body: file:///etc/kratos-jsonnet/debug.jsonnet
              method: POST
              response:
                ignore: true
              url: http://echo-server.default/login
            hook: web_hook
      after:
        default_browser_return_url: https://auth.developer-friendly.blog/login
      enabled: true
      lifespan: 15m
      ui_url: https://auth.developer-friendly.blog/verification
      use: link
  methods:
    code:
      config:
        lifespan: 1h
      enabled: true
    link:
      config:
        lifespan: 1h
      enabled: true
    oidc:
      config:
        providers:
          - id: google
            provider: google
            client_id: OVERRIDDEN_BY_ENVS
            client_secret: OVERRIDDEN_BY_ENVS
            mapper_url: file:///etc/kratos-jsonnet/google.jsonnet
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
      enabled: true
    # profile:
    #   enabled: false
    password:
      enabled: false
    webauthn:
      config:
        rp:
          id: developer-friendly.blog
          display_name: Developer Friendly Blog
          origins:
            - https://auth.developer-friendly.blog
        passwordless: true
      enabled: false
    passkey:
      config:
        rp:
          display_name: Developer Friendly Blog
          id: auth.developer-friendly.blog
          origins:
            - https://auth.developer-friendly.blog
      enabled: false
    totp:
      enabled: true
serve:
  admin:
    port: 4434
    request_log:
      disable_for_health: false
  public:
    base_url: https://auth-server.developer-friendly.blog/
    cors:
      allow_credentials: true
      allowed_headers:
        - Content-Type
      allowed_origins:
        - https://*.developer-friendly.blog
      debug: false
      enabled: true
      # options_passthrough: true
    port: 4433
    request_log:
      disable_for_health: false
session:
  lifespan: 24h
  whoami:
    required_aal: highest_available
# tracing:
#   provider: jaeger
#   providers:
#     jaeger:
#       local_agent_address: jaeger.monitoring:6831
#       sampling:
#         server_url: http://jaeger.monitoring:5778/sampling
#   service_name: kratos
